# Algo TP3 

## Ex 1. Chaine de 0 et 1 qui resoud un UBQP

In [153]:
# Unconstrained Binary Quadratic Problem
def UBGP(matrix,X):
    n = len(matrix)
    m = len(matrix[0])
        
    #result = np.apply_along_axis((lambda row: row*X), axis=1, arr=matrix).sum(axis=1)
    res = 0
    for i in range(len(matrix)):
        for j in range(len(matrix[0])):
            res += matrix[i,j]*X[i]*X[j]
        
    return res

In [154]:
# Read file
def read_file(file_path):
    f = open(file_path, "r")
    content = f.read()
    content = content.replace("\n", "")
    content_list = content.split(" ")
    content_list = list(map(int, content_list))
    n = content_list[0]
    p = content_list[1]
    Q = np.array(content_list[2:])
    Q.shape = ((n,n))
    f.close()
    return(n,p,Q)

In [155]:
import numpy as np

def create_rand_bit_vector(n):
    return [np.random.choice([0,1]) for i in range(n)]

In [224]:
def meilleur_voisin(X,neighbours,p):
    solutions = []
    
    for neighbour in neighbours:
        diff = (np.array(neighbour) == np.array(X))
        if(sum(diff) >= len(X)-1 and  sum(diff)>=p):
            solutions.append(neighbour)
            
    randomRow = np.random.randint(len(solutions), size=1)
            
    return (solutions[randomRow[0]])

In [ ]:
MAX_depl = 5

def steepest_hill_climbing(s):
    nb_depl = 0
    stop = False
    while(True):
        new_s = meilleur_voisin(s)
        if(meilleur(new_s,s)):
            s = new_s
        else:
            stop = true # optimum local
        nb_depl++
        if(not stop and nb_depl != MAX_depl)
            break;
    return s

In [ ]:
for i in range(MAX_essais):
    steepest_hill_climbing(s)

In [ ]:
import queue

def tabou(s, k):
    tabou = queue.Queue()
    nb_depl = 0
    msol = s
    stop = false
    while(True):
        if(not voisins_non_Tabou(s)):
            new_s = meilleur_voisin_non_Tabou(s) #plus de voisin non tabou
        else:
            stop = True
        tabou.put(s)
        if(meilleur(new_s, msol)):
            msol = new_s #stockage meilleure solution courante
            s = new_s
            nb_depl++
        if(nb_depl != MAX_depl and not stop):
            break
    return msol        

In [226]:
Q = []
X = []
n,p,Q = read_file("partition6.txt")
X = create_rand_bit_vector(n)
print(Q)
X = [1,1,0,1,0,0]
print(UBGP(Q,X))
neighboors = [[1,0,0,0,0,0],[1,1,0,1,0,0],[1,1,1,1,0,0],[1, 0, 1, 1, 0, 0]]
print(meilleur_voisin(X, neighboors, p))

[[-17  10  10  10   0  20]
 [ 10 -18  10  10  10  20]
 [ 10  10 -29  10  20  20]
 [ 10  10  10 -19  10  10]
 [  0  10  20  10 -17  10]
 [ 20  20  20  10  10 -28]]
6
[1, 1, 1, 1, 0, 0]


## EX 2 Traveling Salesman